version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres-boilerplate:
    image: postgres:latest
    container_name: postgres-boilerplate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
