name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
      - name: Build Pages
        run: yarn build
      - name: Export Pages
        run: yarn export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
